### ISSUE TITLE
Add "go to localhost:5000 in your browser" to instructions w/in terminal

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-app-generator#1]
![screen shot 2017-03-21 at 1 29 43 pm](https://cloud.githubusercontent.com/assets/5605552/24161327/777a488a-0e3a-11e7-971d-a39ade0759b4.png)

@shea256

**Comment by shea256** [comment]
This is no longer needed as the server automatically opens "localhost:5000" in your browser 🐎
