### ISSUE TITLE
Create a Vue.JS generator

### ISSUE THREAD

**Issue by estermer** [blockstack/blockstack-app-generator#12]
Another popular framework that is growing and from what I have heard is nicer than React.

It is a light weight, component based, client side framework that would be nice to have a generator for.

**Comment by guylepage3** [comment]
Adding a Vue.js app generator would be a great idea as well @estermer

**Comment by jackzampolin** [comment]
This could be accomplished by moving the todo app code into a generator: https://github.com/blockstack/blockstack-todos

**Comment by zone117x** [comment]
The Vue generator has been merged in
