### ISSUE TITLE
generator blockstack:react doesnt exist

### ISSUE THREAD

**Issue by dantrevino** [blockstack/blockstack-app-generator#13]
```
$ npm install -g generator-blockstack      
+ generator-blockstack@0.2.0
updated 1 package in 14.015s
$ yo blockstack:react                      
Error blockstack:react 

You don't seem to have a generator with the name “blockstack:react” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install generator-blockstack:react.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators. 

If yo cannot find the generator, run yo doctor to troubleshoot your system.
```

**Comment by dantrevino** [comment]
$ yo doctor 

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!

**Comment by tacryt-socryp** [comment]
Hi, I also have this issue.

**Comment by tacryt-socryp** [comment]
Workaround:
1. Download the zip file of this repository.
2. `cd to-the-directory`
3. `npm install`
4. `mkdir your-app-name && cd your-app-name`
5. `yo ../generators/react/index.js`

**Comment by jackzampolin** [comment]
Thanks for helping us debug this issue @dantrevino, Its been fixed.
