### ISSUE TITLE
CORS errors in blockstack:react authentication

### ISSUE THREAD

**Issue by Zydnar** [blockstack/blockstack-app-generator#29]
See: [https://forum.blockstack.org/t/dealing-with-cors-errors-in-blockstack-auth-and-react/2592](https://forum.blockstack.org/t/dealing-with-cors-errors-in-blockstack-auth-and-react/2592)
fix is simple - in package.json start command for webpack dev-server should be runned at same origin as blockstack browser:
`"start": "webpack-dev-server --host 127.0.0.1 --port 3000",`

**Comment by hstove** [comment]
Is your native Blockstack Browser opening on 127.0.0.1? Mine opens on localhost, and that's the behavior I've seen for everyone else, too.

**Comment by Zydnar** [comment]
No, it's runned at localhost. 127.0.0.1 is localhost and in this configuration it works with the browser runned at localhost. Anyway if I was the only one after using this generator eccountering this error just mark the issue as invalid. I can check it on other PC later.

**Comment by hstove** [comment]
Ah, I see. Yeah, since both the app and the browser are on localhost, and I haven't been able to reproduce this issue, I'm going to close. Thanks for reaching out!
