### ISSUE TITLE
Issues with Generator cause downstream problems in the hello-world

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack-app-generator#36]
novus-sanguis [6:17 AM]
Hey! I have just started with the blockstack. But I m unable to run the hello-world app. 
-> Can anyone help me by sharing resources on how to set up local development environment?
-> Is it necessary to run a server on hosted domain?

Thanks in advance. (edited)

Ferruccio Balestreri [7:34 AM]
2) is not
1) check my app’s source, you can use it as a boilerplate: https://github.com/ferrucc-io/kit-crm
I had trouble too when starting from the blockstack base project and had to update and add a bunch of libraries to make it usable, let me know if something isn’t clear. setup should be really straightforward as these apps have all the logic client side, so are basically static sites with content hosted on blockstack
I just updated the readme for you @novus-sanguis

moxiegirl [8:00 AM]
Thanks @Ferruccio Balestreri for a quick response. If y'all can slack me the project link you are having problem with, we can see about cleaning that up.  Or even better, file an issue on our repo. That way we can fix it at the source and hopefully help out the next person.
Or, if you don't mind, @Ferruccio Balestreri I'll see what I can update based on your repo?

Ferruccio Balestreri [8:02 AM]
add the new version of webpack & babel
oh and react too

moxiegirl [8:04 AM]
:heavy_check_mark::pray:

Hank [8:05 AM]
just version bumps? we can definitely update the app generator with that

Ferruccio Balestreri [8:05 AM]
it’s a little bit of a pain as the babel files all changed and the webpack confit changed too
version bumps that had breaking changes for config
for version bumps i'd suggest you added https://dependabot.com to the repo
dependabot.com
Dependabot
Automated dependency updates for your Ruby, Python, JavaScript, PHP, .NET, Go, Elixir, Rust, Java and Elm.

**Comment by zone117x** [comment]
@Sahana-Srinivasan's React generator improvements with the `react-scripts` commands fixes this dependency issue
