### ISSUE TITLE
Add Hello Blockstack image to readME and link youtube video

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack-app-generator#4]
@shea256, requesting either the following or to give me permission to edit this repo so I can complete.

upload this file: 
![screen shot 2017-03-30 at 10 56 40 am](https://cloud.githubusercontent.com/assets/5605552/24510576/a3927416-1537-11e7-8213-83d04227c4e4.png)

then hyperlink the Youtube URL: https://youtu.be/UbZ6PlX5rF8 

![screen shot 2017-03-30 at 11 00 44 am](https://cloud.githubusercontent.com/assets/5605552/24510787/26b7442a-1538-11e7-98e0-a87a83498c60.png)

**Comment by jackzampolin** [comment]
Closing as stale. This repo has more than just that now.
