### ISSUE TITLE
Create minimal webpack project template, taking advantage of the blockstack.js substantial size reductions

### ISSUE THREAD

**Issue by zone117x** [blockstack/blockstack-app-generator#40]
Especially after this gets merged https://github.com/blockstack/blockstack.js/pull/614

Also as of webpack v4, it works [without any configuration](https://webpack.js.org/guides/getting-started/#using-a-configuration). Possibly less than the existing, relatively minimal browserify based template. 

If this webpack-based project template is as compatible with existing tutorials geared towards the current default (browserify-based) template, then switch the generator to using this one.

**Comment by zone117x** [comment]
This is done

**Comment by moxiegirl** [comment]
@zone117x the default Javascript is used in Hello-world. That's the default --- full fills the platform promise that an Javascript is supported.

| Framework | Use this command to install |
|------------------|-----------------------------|
| Plain Javascript | `yo blockstack` |
| Webpack | `yo blockstack:webpack` |
| React | `yo blockstack:react` |
| Vue | `yo blockstack:vue` |

If you default to webpack, we will need to create a version to support plain old Javascript. All our tutorials are defaulting to React.  So, it doesn't really make sense to use webpack as the default.
