### ISSUE TITLE
ERROR in index_bundle.js from UglifyJs Unexpected token: name

### ISSUE THREAD

**Issue by mehmetkose** [blockstack/blockstack-app-generator#41]
After the "yarn build" the yeoman:react boilerplate. that was first attempt.

![Screen Shot 2019-03-21 at 17 40 54](https://user-images.githubusercontent.com/706678/54760156-8d8c3d80-4c00-11e9-9f2d-abbc8328c9b6.png)

**Comment by zone117x** [comment]
@mehmetkose Thanks for the report.
@hstove Would you say it makes more sense to rebuild/update the react template, or to try to fix this specific issue?

**Comment by omgitsgod** [comment]
Any idea how I would go about fixing this my own project?

**Comment by iwanether** [comment]
Also running into this issue when trying to build the app.

**Comment by zone117x** [comment]
This should be fixed in latest version. The React generator now uses `react-scripts` which manages dependencies like webpack under the hood. This issue should be fixed now. Just tested with `yarn build`.

Please comment if still running into issues.
