### ISSUE TITLE
script issue

### ISSUE THREAD

**Issue by yangsiabpao** [blockstack/blockstack-app-generator#48]
"scripts": {
    "start": "npm-run-all --parallel reactstart webservice",
    "reactstart": "react-scripts start",
    "webservice": "node server.js",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },

when i have confgured a script as above and i try to start npm start. i have found error as this.
D:\App\sportsstore>npm start

> sportsstore@0.1.0 start D:\App\sportsstore
> npm-run-all --parallel reactstart webservice

> sportsstore@0.1.0 webservice D:\App\sportsstore
> node server.js

> sportsstore@0.1.0 reactstart D:\App\sportsstore
> react-scripts start

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'D:\App\sportsstore\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sportsstore@0.1.0 webservice: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sportsstore@0.1.0 webservice script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pao.y\AppData\Roaming\npm-cache\_logs\2019-05-17T03_55_04_955Z-debug.log
ERROR: "webservice" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sportsstore@0.1.0 start: `npm-run-all --parallel reactstart webservice`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sportsstore@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pao.y\AppData\Roaming\npm-cache\_logs\2019-05-17T03_55_05_197Z-debug.log

this is log file message.
 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\pao.y\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.14.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle sportsstore@0.1.0~prestart: sportsstore@0.1.0
6 info lifecycle sportsstore@0.1.0~start: sportsstore@0.1.0
7 verbose lifecycle sportsstore@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle sportsstore@0.1.0~start: PATH: C:\Users\pao.y\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\App\sportsstore\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Brackets\command;C:\Program Files\nodejs\;C:\Program Files\Microsoft VS Code\bin;C:\Users\pao.y\AppData\Local\Microsoft\WindowsApps;C:\Users\pao.y\AppData\Roaming\npm
9 verbose lifecycle sportsstore@0.1.0~start: CWD: D:\App\sportsstore
10 silly lifecycle sportsstore@0.1.0~start: Args: [ '/d /s /c', 'npm-run-all --parallel reactstart webservice' ]
11 silly lifecycle sportsstore@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle sportsstore@0.1.0~start: Failed to exec start script
13 verbose stack Error: sportsstore@0.1.0 start: `npm-run-all --parallel reactstart webservice`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\pao.y\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\pao.y\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid sportsstore@0.1.0
15 verbose cwd D:\App\sportsstore
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pao.y\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.14.1
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error sportsstore@0.1.0 start: `npm-run-all --parallel reactstart webservice`
22 error Exit status 1
23 error Failed at the sportsstore@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

any advice from all you experts is really appreciated.

best wishes,
Pao

**Comment by zone117x** [comment]
This should be fixed in latest version. Please comment if still running into issues.
