### ISSUE TITLE
Replace current default app generate with the React or Webpack generator

### ISSUE THREAD

**Issue by zone117x** [blockstack/blockstack-app-generator#55]
I'm tempted to say we nuke this template and replace it with either the `react` or `webpack` template. Both of those templates generate a more concise, useful and standard app scaffold than this one. Probably something that should be done in a later PR though.
@moxiegirl @yknl thoughts?

_Originally posted by @zone117x in https://github.com/blockstack/blockstack-app-generator/pull/54_

**Comment by moxiegirl** [comment]
@zone117x Makes sense. My vote would be to standardize on React.  The vast majority of our tutorials use React.

**Comment by zone117x** [comment]
The webpack one is a bit more agnostic and a bit more approachable for the devs who use different frameworks or no framework. I think there is a relevant subset of devs who don't know React and might be thrown off if the default generated implied they needed to learn & use it.

But I'm totally fine with either one. @yknl @hstove any input?

**Comment by yknl** [comment]
+1 for webpack template. I think it would be a nice to have.

**Comment by moxiegirl** [comment]
@zone117x you know, we would still need to allow basic Javascript which is the current default. Here are the currently supported generation methods:

 | Framework | Use this command to install |
 |------------------|-----------------------------|
 | Plain Javascript | `yo blockstack` |
 | Webpack | `yo blockstack:webpack` |
 | React | `yo blockstack:react` |
 | Vue | `yo blockstack:vue` |

 Maybe we can just leave as is --- we make a general platform promise "you can use any" Javascript you want.  Right now the Hello World is using this Javascript template --- which as you can see has no template specification.

**Comment by zone117x** [comment]
The current default isn't plain javascript, at least not any more than the webpack template is.

It's a cobbled together usage of `browserify`, `express`, and `open`, with their corresponding js and package.json scripts. All of which are used to accomplish what can be done with one coherent tool: a) `webpack`, or b) the slightly more opinionated `react-scripts`. 

I brought this issue up as a result of talking with an app dev who, due to misunderstanding of the current default app template, was writing nonsensical code that was useless outside of a local dev environment. Like putting app logic into the `server.js` file.

**Comment by moxiegirl** [comment]
@zone117x Thanks for the clarification. I was going by how it appeared to work.  If you Implement this change, we need to fix the table in the README and the docs.

BTW, we standardized on React because it works correctly in the supported environments. @Sahana-Srinivasan did ensure that the react changes she made worked in both Mac/Windows without trouble.  Please confirm this will be the requirement with any webpack changes.

**Comment by stackatron** [comment]
We discussed: React

**Comment by zone117x** [comment]
This is merged to master. Closing this ticket and creating a new one for updating README with new package generator features.
