### ISSUE TITLE
Clean url with replaceState

### ISSUE THREAD

**Issue by njordhov** [blockstack/blockstack-app-generator#58]
After authentication, cleaning the browser location by setting `window.location` results in untimely refreshing of the page:

````javascript
window.location = window.location.origin
````

Instead, the window location can be cleaned using:

````javascript
window.history.replaceState({}, document.title, "/")
````

The current implementation still requires a refresh unless there are more substantial refactoring of the signin flow. Here is a suggested replacement for the offending `componentWillMount` implementations in App.js that also resolves issue #25 :

 ````javascript
componentDidMount() {
    if (userSession.isSignInPending()) {
      userSession.handlePendingSignIn().then((userData) => {
        // window.location = window.location.origin;
        window.history.replaceState({}, document.title, "/")
        this.setState({ userData: userData})
      });
    }
  }
````

**Comment by zone117x** [comment]
Could you make a PR with this changes? Looks like something we would merge.
