### ISSUE TITLE
Update README with new package init features

### ISSUE THREAD

**Issue by zone117x** [blockstack/blockstack-app-generator#68]
The changes from this PR https://github.com/blockstack/blockstack-app-generator/pull/67 need captured in the README around the same time a new npm package is published.

@moxiegirl Should we create a different ticket for the tutorial/doc changes?

**Comment by moxiegirl** [comment]
@zone117x I've added Needs user Docs. When I remove that label, I'll add a comment on here that it is done.  That way, we don't have to duplicate tickets all over.

**Comment by zone117x** [comment]
Closed with https://github.com/blockstack/blockstack-app-generator/pull/63
