### ISSUE TITLE
Create different framework generators

### ISSUE THREAD

**Issue by estermer** [blockstack/blockstack-app-generator#8]
I Just created a generator for React.JS #6, but there are a couple nice frameworks out there that would be cool to get a generator for:

- jQuery
- Angular.JS 1 & 2
- Vue.JS
- Ember.JS
- Backbone.JS
- Polymer.JS

Just to name a few.

I would like to work on some of these over time but I don't know ember, backbone, or polymer so if someone could take up the task.

**Comment by jackzampolin** [comment]
I'm going to open seperate feature request issues for each of these.
