### ISSUE TITLE
Add support for app manifests

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-app-generator#9]
Current versions of blockstack.js & portal require an app manifest is provided as part of a valid authentication request

**Comment by larrysalibra** [comment]
<img width="557" alt="screen shot 2017-05-08 at 11 54 45 pm" src="https://cloud.githubusercontent.com/assets/597182/25812732/cce1a8e2-3449-11e7-9c83-8c98c0f7bf3e.png">

**Comment by jackzampolin** [comment]
This feature has been added to the app. Closing.
